CMS ARS 3.1 AWS RDS Moderate Overlay
CMSgov/cms-ars-3.1-moderate-aws-rds-microsoft-sql-server-2017-cis-overlay pull request #1
Opened 2022-05-04 15:11 UTC by karikarshivani

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

2022-05-04 15:12 UTC, karikarshivani commented on inspec.yml
> +  url: https://github.com/mitre/microsoft-sql-server-2017-cis-baseline/archive/v1.2.0.tar.gz
I'll update the branch name in the `depends.url` when the PR for the baseline has been approved and merged. Thanks!

2022-06-09 22:18 UTC, ejaronne requested changes
update depends reference to main.tar.gz (not 1.2.0)
update README exec instructions to use main.tar.gz (not master)
update README "full heimdall server" url to point to heimdall2 repo not old heimdall

2022-06-10 02:11 UTC, ejaronne approved these changes
typo corrections in README and inspec.yml added

2022-06-10 18:03 UTC, karikarshivani commented on inspec.yml
> +  url: https://github.com/mitre/microsoft-sql-server-2017-cis-baseline/archive/v1.2.0.tar.gz
Branch name updated

2022-06-10 18:04 UTC, karikarshivani commented
Profile tested - ready to be merged. Thanks!

2022-06-11 15:15 UTC, merged